name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: go test ./... -coverprofile=profile.cov
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: make lint
